spring:
  application:
    name: donations
  docker:
    compose:
      enabled: false
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/donations?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate (JPA) Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    mappings:
      enabled: true

daraja:
  configs:
    consumer-key: ${DARAJA_CONSUMER_KEY}
    consumer-secret: ${DARAJA_CONSUMER_SECRET}
    security-credential: ${DARAJA_SECURITY_CREDENTIAL}
    auth-url: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
    base-url: https://e41a-2c0f-fe38-2326-8c7e-b5d5-f8f4-e4ff-c0b0.ngrok-free.app
    b2c-url: https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest
    b2c-initiator-name: ${DARAJA_B2C_INITIATOR_NAME}
    b2c-initiator-password: ${DARAJA_B2C_INITIATOR_PASSWORD}
    b2c-party-a: 600999
    b2c-initiate-url: /momo/b2c-initiate
    b2c-callback-url: /momo/b2c-callback
    b2c-result-url: /momo/b2c-result
    c2b-short-code: 600983
    c2b-register-url-url: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    c2b-register-call-url: /momo/c2b-register-call
    c2b-confirmation-url: /momo/c2b-confirmation
    c2b-validation-url: /momo/c2b-validation
    c2b-simulate-url: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    query-transaction-url: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
    query-transaction-call-url: /momo/query-transaction-call
    query-transaction-queue-url: /momo/query-transaction-queue
    query-transaction-result: /momo/query-transaction-result
    query-bal-url: https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query
    query-bal-queue-url: /momo/query-bal-queue
    query-bal-result-url: /momo/query-bal-result
    query-bal-call-url: /momo/query-bal-call
    reversal-url: https://sandbox.safaricom.co.ke/mpesa/reversal/v1/request
    reversal-queue-url: /momo/reversal-queue
    reversal-result-url: /momo/reversal-result
    reversal-call-url: /momo/reversal-call
    remit-tax-url: https://sandbox.safaricom.co.ke/mpesa/b2b/v1/remittax
    remit-tax-queue-url: /momo/remittax-queue
    remit-tax-result-url: /momo/remittax-result
    remit-tax-call-url: /momo/remittax-call
